/**
 * 本体控制台 · 静态数据层（与路由 query 联动）
 */
(function () {
  var D = {
    meta: {
      product: '华曦 · 企业本体管理平台',
      refreshedAt: '2026-03-21 09:30 CST',
      tenant: '澄泓控股',
      env: '生产',
    },
    kpi: [
      { id: 'ot', label: '对象类型', value: '52', sub: '+4 本月', trend: 'up', icon: 'category' },
      { id: 'inst', label: '对象实例', value: '128.4 万', sub: '在线 126.9 万', trend: 'up', icon: 'database' },
      { id: 'act', label: '动作执行（24h）', value: '18,204', sub: '成功率 99.72%', trend: 'flat', icon: 'bolt' },
      { id: 'sync', label: '集成同步作业', value: '312', sub: '失败 3 · 已重试', trend: 'down', icon: 'sync' },
    ],
    namespaces: [
      { id: 'ns-core', name: 'business_core', title: '核心业务域', desc: '客户 / 合同 / 组织机构', count: 23 },
      { id: 'ns-hr', name: 'hr_system', title: '人力资源', desc: '员工 / 岗位 / 汇报链', count: 11 },
      { id: 'ns-fin', name: 'finance_ops', title: '财务运营', desc: '发票 / 成本中心 / 预算单元', count: 9 },
      { id: 'ns-supply', name: 'supply_chain', title: '供应链', desc: '供应商 / 采购订单 / 库存点位', count: 9 },
    ],
    objectTypes: [
      { id: 'ot-cust', name: '企业客户', ns: 'business_core', props: 34, iface: ['Party', 'Auditable'], inst: 42890, health: 98, owner: '本体架构组', updated: '2026-03-19' },
      { id: 'ot-cont', name: '框架协议', ns: 'business_core', props: 28, iface: ['Contractual', 'Auditable'], inst: 12056, health: 99, owner: '法务技术组', updated: '2026-03-18' },
      { id: 'ot-emp', name: '在岗员工', ns: 'hr_system', props: 41, iface: ['Person', 'Party'], inst: 35602, health: 97, owner: '人力数字化', updated: '2026-03-20' },
      { id: 'ot-org', name: '组织单元', ns: 'hr_system', props: 19, iface: ['HierarchyNode'], inst: 4120, health: 100, owner: '人力数字化', updated: '2026-03-17' },
      { id: 'ot-sku', name: '主数据物料', ns: 'supply_chain', props: 56, iface: ['MasterEntity'], inst: 89200, health: 96, owner: '供应链中台', updated: '2026-03-19' },
      { id: 'ot-inv', name: '销售发票', ns: 'finance_ops', props: 22, iface: ['Auditable'], inst: 210033, health: 99, owner: '财务共享中心', updated: '2026-03-20' },
      { id: 'ot-vend', name: '供应商', ns: 'supply_chain', props: 31, iface: ['Party', 'Auditable'], inst: 6240, health: 97, owner: '供应链中台', updated: '2026-03-18' },
      { id: 'ot-po', name: '采购订单', ns: 'supply_chain', props: 44, iface: ['Contractual'], inst: 156200, health: 98, owner: '采购数字化', updated: '2026-03-20' },
      { id: 'ot-prj', name: '研发项目', ns: 'business_core', props: 27, iface: ['Auditable'], inst: 890, health: 95, owner: '研发管理部', updated: '2026-03-15' },
      { id: 'ot-asset', name: '固定资产', ns: 'finance_ops', props: 38, iface: ['MasterEntity'], inst: 12400, health: 99, owner: '资产管理', updated: '2026-03-12' },
    ],
    objectTypeDetails: {
      'ot-cust': {
        id: 'ot-cust',
        name: '企业客户',
        apiName: 'EnterpriseCustomer',
        ns: 'business_core',
        version: 'v2.14.0',
        description: '统一集团视角的企业客户主数据，对齐 MDM 金标与 CRM 来源；支持多法人、多账套视图。',
        properties: [
          { name: 'customerId', type: 'String', pk: true, indexed: true, lineage: 'MDM→金标编码' },
          { name: 'legalName', type: 'String', pk: false, indexed: true, lineage: 'CRM+工商年报' },
          { name: 'creditTier', type: 'Enum', pk: false, indexed: true, lineage: '风控模型输出' },
          { name: 'annualRevenue', type: 'Decimal', pk: false, indexed: false, lineage: '财报抽取+估值补全' },
          { name: 'primaryIndustry', type: 'String', pk: false, indexed: true, lineage: '行业分类国标' },
        ],
        interfaces: ['Party', 'Auditable', 'Geolocatable'],
        linkTypes: ['客户—签署—合同', '客户—隶属—集团', '客户—对接—客户经理'],
      },
      'ot-cont': {
        id: 'ot-cont',
        name: '框架协议',
        apiName: 'FrameworkAgreement',
        ns: 'business_core',
        version: 'v1.9.2',
        description: '战略级框架协议头信息，与法人主体、付款条款、续约策略绑定。',
        properties: [
          { name: 'contractId', type: 'String', pk: true, indexed: true, lineage: 'CLM 系统' },
          { name: 'effectiveDate', type: 'Date', pk: false, indexed: true, lineage: '法务归档' },
          { name: 'totalValue', type: 'Money', pk: false, indexed: false, lineage: '财务汇总' },
        ],
        interfaces: ['Contractual', 'Auditable'],
        linkTypes: ['客户—签署—框架协议', '协议—关联—子订单'],
      },
      'ot-emp': {
        id: 'ot-emp',
        name: '在岗员工',
        apiName: 'ActiveEmployee',
        ns: 'hr_system',
        version: 'v4.1.0',
        description: '在岗人员主数据，与组织、编制、成本中心联动。',
        properties: [
          { name: 'employeeId', type: 'String', pk: true, indexed: true, lineage: 'HR Core' },
          { name: 'displayName', type: 'String', pk: false, indexed: true, lineage: '企业微信' },
          { name: 'costCenter', type: 'String', pk: false, indexed: true, lineage: '财务主数据' },
        ],
        interfaces: ['Person', 'Party'],
        linkTypes: ['员工—任职于—组织单元', '员工—汇报给—员工'],
      },
    },
    linkTypes: [
      { id: 'lt1', name: '客户—签署—框架协议', from: '企业客户', to: '框架协议', card: '1:N', directed: true, owner: '李维' },
      { id: 'lt2', name: '员工—任职于—组织单元', from: '在岗员工', to: '组织单元', card: 'N:1', directed: true, owner: '陈潇' },
      { id: 'lt3', name: '物料—供货—供应商', from: '主数据物料', to: '供应商', card: 'N:N', directed: false, owner: '赵启明' },
      { id: 'lt4', name: '发票—关联—采购订单', from: '销售发票', to: '采购订单', card: '1:N', directed: true, owner: '周颖' },
      { id: 'lt5', name: '项目—服务—客户', from: '研发项目', to: '企业客户', card: 'N:1', directed: true, owner: '王珂' },
      { id: 'lt6', name: '订单—行项目—物料', from: '采购订单', to: '主数据物料', card: '1:N', directed: true, owner: '供应链中台' },
    ],
    instances: [
      { id: 'CUST-009281', typeId: 'ot-cust', type: '企业客户', name: '云岭数字产业基金', tier: 'S', industry: '金融服务', city: '上海', ns: 'business_core', updated: '2026-03-20 14:22' },
      { id: 'CUST-009044', typeId: 'ot-cust', type: '企业客户', name: '江涵精密制造股份有限公司', tier: 'A', industry: '高端装备', city: '苏州', ns: 'business_core', updated: '2026-03-20 11:05' },
      { id: 'CUST-008901', typeId: 'ot-cust', type: '企业客户', name: '青潮消费科技（杭州）', tier: 'B', industry: '零售科技', city: '杭州', ns: 'business_core', updated: '2026-03-19 18:40' },
      { id: 'EMP-120883', typeId: 'ot-emp', type: '在岗员工', name: '刘畅', tier: '—', industry: '人力', city: '北京', ns: 'hr_system', updated: '2026-03-21 08:12' },
      { id: 'SKU-882301', typeId: 'ot-sku', type: '主数据物料', name: '六轴机械臂 RM-6000', tier: '—', industry: '供应链', city: '—', ns: 'supply_chain', updated: '2026-03-18 09:55' },
      { id: 'CUST-007612', typeId: 'ot-cust', type: '企业客户', name: '北辰港口物流集团', tier: 'A', industry: '交通物流', city: '天津', ns: 'business_core', updated: '2026-03-17 16:30' },
      { id: 'VEND-00402', typeId: 'ot-vend', type: '供应商', name: '鑫泰电机（无锡）有限公司', tier: 'A', industry: '制造', city: '无锡', ns: 'supply_chain', updated: '2026-03-20 10:11' },
      { id: 'PO-992831', typeId: 'ot-po', type: '采购订单', name: '华东区 Q1 备件集中采购', tier: '—', industry: '供应链', city: '—', ns: 'supply_chain', updated: '2026-03-19 15:40' },
      { id: 'INV-22109', typeId: 'ot-inv', type: '销售发票', name: 'INV-2026-022109', tier: '—', industry: '财务', city: '—', ns: 'finance_ops', updated: '2026-03-18 11:22' },
      { id: 'PRJ-0088', typeId: 'ot-prj', type: '研发项目', name: '本体引擎 3.x 架构升级', tier: '—', industry: '研发', city: '上海', ns: 'business_core', updated: '2026-03-16 09:00' },
      { id: 'ORG-4401', typeId: 'ot-org', type: '组织单元', name: '数字化中心 / 数据平台部', tier: '—', industry: '组织', city: '上海', ns: 'hr_system', updated: '2026-03-14 13:20' },
      { id: 'CUST-009500', typeId: 'ot-cust', type: '企业客户', name: '瀚海云链科技', tier: 'S', industry: '云计算', city: '深圳', ns: 'business_core', updated: '2026-03-21 07:45' },
    ],
    instanceDetails: {
      'CUST-009281': {
        id: 'CUST-009281',
        typeId: 'ot-cust',
        type: '企业客户',
        name: '云岭数字产业基金',
        props: {
          customerId: 'CUST-009281',
          legalName: '云岭数字产业投资基金（有限合伙）',
          creditTier: 'S',
          annualRevenue: '¥ 4.2 亿（估算）',
          primaryIndustry: 'J66 货币金融服务',
          dataSteward: '马清扬',
          lastVerified: '2026-03-19',
        },
        relatedCounts: { contracts: 12, contacts: 6, opportunities: 3 },
      },
      'CUST-009044': {
        id: 'CUST-009044',
        typeId: 'ot-cust',
        type: '企业客户',
        name: '江涵精密制造股份有限公司',
        props: {
          customerId: 'CUST-009044',
          legalName: '江涵精密制造股份有限公司',
          creditTier: 'A',
          annualRevenue: '¥ 18.6 亿',
          primaryIndustry: 'C34 通用设备制造',
          dataSteward: '孙艺',
          lastVerified: '2026-03-18',
        },
        relatedCounts: { contracts: 28, contacts: 14, opportunities: 7 },
      },
      'EMP-120883': {
        id: 'EMP-120883',
        typeId: 'ot-emp',
        type: '在岗员工',
        name: '刘畅',
        props: {
          employeeId: 'EMP-120883',
          displayName: '刘畅',
          costCenter: 'CC-华东-0012',
          title: '高级数据架构师',
          orgPath: '澄泓控股 / 数字化中心 / 数据平台部',
          hireDate: '2019-04-01',
        },
        relatedCounts: { contracts: 0, contacts: 0, opportunities: 0 },
      },
      'SKU-882301': {
        id: 'SKU-882301',
        typeId: 'ot-sku',
        type: '主数据物料',
        name: '六轴机械臂 RM-6000',
        props: {
          materialId: 'SKU-882301',
          category: '工业自动化 / 机器人',
          unit: '台',
          lifecycle: '量产',
          drawingNo: 'DWG-RM6000-RevF',
        },
        relatedCounts: { contracts: 4, contacts: 0, opportunities: 0 },
      },
    },
    objectSets: [
      { id: 'os-1', name: '战略客户池（华东）', type: '动态', rule: 'tier ∈ {S,A} ∧ region=华东 ∧ active_contract>0', count: 1840, owner: '战略客户部' },
      { id: 'os-2', name: '本月新准入供应商', type: '快照', rule: 'snapshot @ 2026-03-01', count: 96, owner: '供应链风控' },
      { id: 'os-3', name: '高舆情风险客户', type: '动态', rule: 'risk_score>0.82 ∨ watchlist=true', count: 41, owner: '合规办公室' },
      { id: 'os-4', name: '双周对账异常发票', type: '动态', rule: 'reconcile_status=exception ∧ age<14d', count: 127, owner: '财务共享中心' },
    ],
    actions: [
      { id: 'act-approve', name: '客户准入复核', type: '审批流', runs24h: 420, p95: '1.2s', status: '健康', owner: '流程平台' },
      { id: 'act-merge', name: '客户主体归并', type: '事务', runs24h: 38, p95: '8.4s', status: '健康', owner: 'MDM' },
      { id: 'act-sync', name: 'SAP 供应商回写', type: '集成', runs24h: 156, p95: '2.1s', status: '注意', owner: '集成中台' },
      { id: 'act-lineage', name: '属性血缘重算', type: '批处理', runs24h: 6, p95: '6m12s', status: '健康', owner: '数据工程' },
      { id: 'act-notify', name: '合同到期预警', type: '定时', runs24h: 890, p95: '340ms', status: '健康', owner: '法务技术组' },
    ],
    actionDetails: {
      'act-approve': {
        id: 'act-approve',
        name: '客户准入复核',
        version: 'v3.2',
        inputs: [
          { name: 'customerId', type: 'String', required: true },
          { name: 'applyChannel', type: 'Enum', required: true },
          { name: 'attachments', type: 'FileRef[]', required: false },
        ],
        preconditions: [
          '对象类型「企业客户」存在且未处于 merge_pending',
          '申请人角色 ∈ {客户经理, 渠道运营}',
          '幂等键 approvalKey 未在 24h 内重复使用',
        ],
        logic:
          'when creditTier in ["A","B","S"] and riskScore < 0.65:\n  transition(status, "pending_kyc", "approved_fast_track")\nelse:\n  transition(status, "pending_kyc", "manual_review")\nemit("Customer.Approved", payload)',
        webhooks: ['https://hooks.internal.chenghong/notify/crm', 'https://hooks.internal.chenghong/audit/mdm'],
      },
      'act-merge': {
        id: 'act-merge',
        name: '客户主体归并',
        version: 'v1.4',
        inputs: [
          { name: 'survivorId', type: 'String', required: true },
          { name: 'duplicateIds', type: 'String[]', required: true },
        ],
        preconditions: ['两记录均未被锁定', '归并策略已通过风控预审'],
        logic: 'mergeGraph(survivorId, duplicateIds)\nemit("Customer.Merged", { survivorId, duplicateIds })',
        webhooks: ['https://hooks.internal.chenghong/mdm/merge-complete'],
      },
      'act-sync': {
        id: 'act-sync',
        name: 'SAP 供应商回写',
        version: 'v2.0.1',
        inputs: [{ name: 'vendorBatch', type: 'BatchRef', required: true }],
        preconditions: ['连接器 SAP_PRD 状态=运行中', '批次未处于死信队列'],
        logic: 'pushToSap(vendorBatch)\nretry(3, backoff="exponential")',
        webhooks: ['https://hooks.internal.chenghong/sap/callback'],
      },
    },
    graphNodes: [
      { id: 'n1', label: '企业客户', kind: 'type', hrefType: 'ot-cust' },
      { id: 'n2', label: '框架协议', kind: 'type', hrefType: 'ot-cont' },
      { id: 'n3', label: '云岭基金', kind: 'inst', instanceId: 'CUST-009281' },
      { id: 'n4', label: '合同 HT-2026-0092', kind: 'inst', instanceId: null },
    ],
    versions: [
      { tag: 'v2.14.0', date: '2026-03-19', author: '本体架构组', notes: '企业客户新增 annualRevenue 血缘绑定；接口 Party 对齐 v1.8' },
      { tag: 'v2.13.2', date: '2026-03-12', author: '李维', notes: '关联类型「客户—签署—框架协议」基数由 1:1 调整为 1:N' },
      { tag: 'v2.13.0', date: '2026-03-02', author: '数据工程', notes: 'Event Sourcing 回放窗口扩展至 180 天' },
      { tag: 'v2.12.5', date: '2026-02-18', author: '合规办公室', notes: 'RBAC 属性级策略模板：客户证件号脱敏' },
      { tag: 'v2.12.0', date: '2026-02-01', author: '集成中台', notes: 'SAP 连接器支持批量回写与幂等键' },
    ],
    lineageFlow: [
      { step: '金蝶 ERP · 客户主档', system: 'K3 Cloud', latency: '15 min', quality: 99.1 },
      { step: '数据中台 · 标准化映射', system: '自研 ETL', latency: '8 min', quality: 99.6 },
      { step: 'MDM · 黄金记录合并', system: 'Informatica MDM', latency: '22 min', quality: 99.4 },
      { step: '本体 · 企业客户实例', system: '华曦本体', latency: '实时', quality: 99.7 },
    ],
    rbac: {
      roles: ['本体管理员', '业务建模师', '数据运营', '审计只读', '集成开发'],
      resources: ['对象类型', '对象实例', '动作执行', '血缘查看', '版本回滚'],
      matrix: [
        [true, true, true, true, true],
        [true, true, false, true, false],
        [false, true, true, true, false],
        [true, true, false, true, false],
        [false, false, true, false, false],
      ],
    },
    integrations: [
      { id: 'int-sap', name: 'SAP S/4HANA · 供应商', status: '运行中', last: '2026-03-21 09:12', throughput: '1.2k 条/h', owner: '集成中台' },
      { id: 'int-sf', name: 'Salesforce CRM · 客户', status: '运行中', last: '2026-03-21 09:28', throughput: '4.8k 条/h', owner: 'CRM 团队' },
      { id: 'int-fs', name: '飞书审批 · 客户准入', status: '降级', last: '2026-03-20 22:01', throughput: '—', owner: '流程平台' },
      { id: 'int-wx', name: '企业微信 · 组织通讯录', status: '运行中', last: '2026-03-21 07:00', throughput: '同步日批', owner: '人力数字化' },
      { id: 'int-k3', name: '金蝶 K3 · 财务凭证', status: '运行中', last: '2026-03-21 06:30', throughput: '9.1k 条/h', owner: '财务共享中心' },
    ],
    webhookLog: [
      { ts: '2026-03-21 09:27:01', event: 'Action.Customer.Approved', dest: 'crm-hooks', code: 200 },
      { ts: '2026-03-21 09:26:58', event: 'ObjectInstance.Updated', dest: 'audit-bus', code: 200 },
      { ts: '2026-03-21 09:24:11', event: 'Action.Merge.Requested', dest: 'mdm-hooks', code: 503 },
      { ts: '2026-03-21 09:24:12', event: 'Action.Merge.Requested', dest: 'mdm-hooks', code: 200 },
      { ts: '2026-03-21 09:20:00', event: 'Connector.Sap.BatchComplete', dest: 'monitoring', code: 204 },
      { ts: '2026-03-21 09:15:44', event: 'Lineage.Recompute.Done', dest: 'data-catalog', code: 200 },
    ],
    activity: [
      { time: '09:28', user: '系统', action: '批处理 · 属性血缘重算完成', scope: 'finance_ops' },
      { time: '09:14', user: '马清扬', action: '审核通过 · 云岭基金 准入', scope: 'business_core' },
      { time: '08:55', user: '赵启明', action: '发布 · 关联类型 物料—供货—供应商', scope: 'supply_chain' },
      { time: '08:12', user: '刘畅', action: '更新实例 · EMP-120883 岗位信息', scope: 'hr_system' },
      { time: '07:45', user: '系统', action: '同步 · Salesforce 增量 4.2k 条', scope: 'business_core' },
      { time: '07:02', user: '周颖', action: '回滚事件 · v2.13.2 预演环境', scope: 'finance_ops' },
    ],
    chartTrend: {
      labels: ['3/15', '3/16', '3/17', '3/18', '3/19', '3/20', '3/21'],
      instances: [126.2, 126.5, 126.7, 127.1, 127.4, 128.0, 128.4],
      actions: [15200, 15820, 16102, 16440, 17002, 17550, 18204],
    },
  };

  window.ONT_DATA = D;
  window.DEMO_MOCK = D;
})();
